.. # Use http://b64.io/ to encode any image to base64. Then replace `/` with
   # `%2F` and `+` with `%2B` (or use http://meyerweb.com/eric/tools/dencoder/).
   # Beware that `?logo=data:image/png;base64,` must also be converted to
   # percent encoding so that the URL is properly parsed.

.. # Sourcecode link to GitHub
.. |SHIELD:svg:ProjectModel-github| image:: https://img.shields.io/badge/pyEDAA-ProjectModel-ab47bc.svg?longCache=true&style=flat-square&logo=github&longCache=true&logo=GitHub&labelColor=6a1b9a
   :alt: Sourcecode on GitHub
   :height: 22
   :target: https://github.com/edaa-org/pyEDAA.ProjectModel
.. |SHIELD:png:ProjectModel-github| image:: https://raster.shields.io/badge/pyEDAA-ProjectModel-ab47bc.svg?longCache=true&style=flat-square&logo=github&longCache=true&logo=GitHub&labelColor=6a1b9a
   :alt: Sourcecode on GitHub
   :height: 22
   :target: https://github.com/edaa-org/pyEDAA.ProjectModel

.. # Sourcecode license
.. |SHIELD:svg:ProjectModel-src-license| image:: https://img.shields.io/pypi/l/pyEDAA.ProjectModel?longCache=true&style=flat-square&logo=Apache&label=code%20license
   :alt: Code license
   :height: 22
   :target: Code-License.html
.. |SHIELD:png:ProjectModel-src-license| image:: https://img.shields.io/pypi/l/pyEDAA.ProjectModel?longCache=true&style=flat-square&logo=Apache&label=code%20license
   :alt: Code license
   :height: 22
   :target: https://github.com/edaa-org/pyEDAA.ProjectModel/blob/main/LICENSE.md

.. # GitHub tag
.. |SHIELD:svg:ProjectModel-tag| image:: https://img.shields.io/github/v/tag/edaa-org/pyEDAA.ProjectModel?longCache=true&style=flat-square&logo=GitHub&include_prereleases
   :alt: GitHub tag (latest SemVer incl. pre-release
   :height: 22
   :target: https://github.com/edaa-org/pyEDAA.ProjectModel/tags
.. |SHIELD:png:ProjectModel-tag| image:: https://raster.shields.io/github/v/tag/edaa-org/pyEDAA.ProjectModel?longCache=true&style=flat-square&logo=GitHub&include_prereleases
   :alt: GitHub tag (latest SemVer incl. pre-release
   :height: 22
   :target: https://github.com/edaa-org/pyEDAA.ProjectModel/tags

.. # GitHub release date
.. |SHIELD:svg:ProjectModel-date| image:: https://img.shields.io/github/release-date/edaa-org/pyEDAA.ProjectModel?longCache=true&style=flat-square&logo=GitHub
   :alt: GitHub release date
   :height: 22
   :target: https://github.com/edaa-org/pyEDAA.ProjectModel/releases
.. |SHIELD:png:ProjectModel-date| image:: https://raster.shields.io/github/release-date/edaa-org/pyEDAA.ProjectModel?longCache=true&style=flat-square&logo=GitHub
   :alt: GitHub release date
   :height: 22
   :target: https://github.com/edaa-org/pyEDAA.ProjectModel/releases

.. # GitHub/Libraries dependent projects
.. |SHIELD:svg:ProjectModel-lib-dep| image:: https://img.shields.io/librariesio/dependent-repos/pypi/pyEDAA.ProjectModel?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Dependent repos (via libraries.io)
   :height: 22
   :target: https://github.com/edaa-org/pyEDAA.ProjectModel/network/dependents
.. |SHIELD:png:ProjectModel-lib-dep| image:: https://raster.shields.io/librariesio/dependent-repos/pypi/pyEDAA.ProjectModel?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Dependent repos (via libraries.io)
   :height: 22
   :target: https://github.com/edaa-org/pyEDAA.ProjectModel/network/dependents

.. # GHA test and coverage
.. |SHIELD:svg:ProjectModel-gha-test| image:: https://img.shields.io/github/workflow/status/edaa-org/pyEDAA.ProjectModel/Unit%20Testing,%20Coverage%20Collection,%20Package,%20Release,%20Documentation%20and%20Publish/master?longCache=true&style=flat-square&label=Build%20and%20Test&logo=GitHub%20Actions&logoColor=FFFFFF
   :alt: GitHub Workflow - Build and Test Status
   :height: 22
   :target: https://github.com/edaa-org/pyEDAA.ProjectModel/actions?query=workflow%3A%22Unit%20Testing,%20Coverage%20Collection,%20Package,%20Release,%20Documentation%20and%20Publish%22
.. |SHIELD:png:ProjectModel-gha-test| image:: https://img.shields.io/github/workflow/status/edaa-org/pyEDAA.ProjectModel/Unit%20Testing,%20Coverage%20Collection,%20Package,%20Release,%20Documentation%20and%20Publish/master?longCache=true&style=flat-square&label=Build%20and%20Test&logo=GitHub%20Actions&logoColor=FFFFFF
   :alt: GitHub Workflow - Build and Test Status
   :height: 22
   :target: https://github.com/edaa-org/pyEDAA.ProjectModel/actions?query=workflow%3A%22Unit%20Testing,%20Coverage%20Collection,%20Package,%20Release,%20Documentation%20and%20Publish%22

.. # Codacy - quality
.. |SHIELD:svg:ProjectModel-codacy-quality| image:: https://img.shields.io/codacy/grade/c2635df20fa840bc85639ca2fa1d9cb4?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Quality
   :height: 22
   :target: https://www.codacy.com/manual/edaa-org/pyEDAA.ProjectModel
.. |SHIELD:png:ProjectModel-codacy-quality| image:: https://raster.shields.io/codacy/grade/c2635df20fa840bc85639ca2fa1d9cb4?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Quality
   :height: 22
   :target: https://www.codacy.com/manual/edaa-org/pyEDAA.ProjectModel

.. # Codacy - coverage
.. |SHIELD:svg:ProjectModel-codacy-coverage| image:: https://img.shields.io/codacy/coverage/c2635df20fa840bc85639ca2fa1d9cb4?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Line Coverage
   :height: 22
   :target: https://www.codacy.com/manual/edaa-org/pyEDAA.ProjectModel
.. |SHIELD:png:ProjectModel-codacy-coverage| image:: https://raster.shields.io/codacy/coverage/c2635df20fa840bc85639ca2fa1d9cb4?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Line Coverage
   :height: 22
   :target: https://www.codacy.com/manual/edaa-org/pyEDAA.ProjectModel

.. # Codecov - coverage
.. |SHIELD:svg:ProjectModel-codecov-coverage| image:: https://img.shields.io/codecov/c/github/edaa-org/pyEDAA.ProjectModel?longCache=true&style=flat-square&logo=Codecov
   :alt: Codecov - Branch Coverage
   :height: 22
   :target: https://codecov.io/gh/edaa-org/pyEDAA.ProjectModel
.. |SHIELD:png:ProjectModel-codecov-coverage| image:: https://raster.shields.io/codecov/c/github/edaa-org/pyEDAA.ProjectModel?longCache=true&style=flat-square&logo=Codecov
   :alt: Codecov - Branch Coverage
   :height: 22
   :target: https://codecov.io/gh/edaa-org/pyEDAA.ProjectModel

.. # Libraries - source rank
.. |SHIELD:svg:ProjectModel-lib-rank| image:: https://img.shields.io/librariesio/sourcerank/pypi/pyEDAA.ProjectModel?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io SourceRank
   :height: 22
   :target: https://libraries.io/github/edaa-org/pyEDAA.ProjectModel/sourcerank
.. |SHIELD:png:ProjectModel-lib-rank| image:: https://raster.shields.io/librariesio/sourcerank/pypi/pyEDAA.ProjectModel?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io SourceRank
   :height: 22
   :target: https://libraries.io/github/edaa-org/pyEDAA.ProjectModel/sourcerank

.. # PyPI tag
.. |SHIELD:svg:ProjectModel-pypi-tag| image:: https://img.shields.io/pypi/v/pyEDAA.ProjectModel?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Tag
   :height: 22
   :target: https://pypi.org/project/pyEDAA.ProjectModel/
.. |SHIELD:png:ProjectModel-pypi-tag| image:: https://raster.shields.io/pypi/v/pyEDAA.ProjectModel?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Tag
   :height: 22
   :target: https://pypi.org/project/pyEDAA.ProjectModel/

.. # PyPI project status
.. |SHIELD:svg:ProjectModel-pypi-status| image:: https://img.shields.io/pypi/status/pyEDAA.ProjectModel?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Status
   :height: 22
.. |SHIELD:png:ProjectModel-pypi-status| image:: https://raster.shields.io/pypi/status/pyEDAA.ProjectModel?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Status
   :height: 22

.. # PyPI Python versions
.. |SHIELD:svg:ProjectModel-pypi-python| image:: https://img.shields.io/pypi/pyversions/pyEDAA.ProjectModel?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Python Version
   :height: 22
.. |SHIELD:png:ProjectModel-pypi-python| image:: https://raster.shields.io/pypi/pyversions/pyEDAA.ProjectModel?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Python Version
   :height: 22

.. # Libraries - status
.. |SHIELD:svg:ProjectModel-lib-status| image:: https://img.shields.io/librariesio/release/pypi/pyEDAA.ProjectModel?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io status for latest release
   :height: 22
   :target: https://libraries.io/github/edaa-org/pyEDAA.ProjectModel
.. |SHIELD:png:ProjectModel-lib-status| image:: https://raster.shields.io/librariesio/release/pypi/pyEDAA.ProjectModel?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io status for latest release
   :height: 22
   :target: https://libraries.io/github/edaa-org/pyEDAA.ProjectModel

.. # Requires - status
.. |SHIELD:svg:ProjectModel-req-status| image:: https://img.shields.io/requires/github/edaa-org/pyEDAA.ProjectModel?longCache=true&style=flat-square
   :alt: Requires.io
   :height: 22
   :target: https://requires.io/github/edaa-org/pyEDAA.ProjectModel/requirements/?branch=main
.. |SHIELD:png:ProjectModel-req-status| image:: https://raster.shields.io/requires/github/edaa-org/pyEDAA.ProjectModel?longCache=true&style=flat-square
   :alt: Requires.io
   :height: 22
   :target: https://requires.io/github/edaa-org/pyEDAA.ProjectModel/requirements/?branch=main

.. # Documentation license
.. |SHIELD:svg:ProjectModel-doc-license| image:: https://img.shields.io/badge/doc%20license-CC--BY%204.0-green?longCache=true&style=flat-square&logo=CreativeCommons&logoColor=fff
   :alt: Documentation License
   :height: 22
   :target: License.html
.. |SHIELD:png:ProjectModel-doc-license| image:: https://raster.shields.io/badge/doc%20license-CC--BY%204.0-green?longCache=true&style=flat-square&logo=CreativeCommons&logoColor=fff
   :alt: Documentation License
   :height: 22
   :target: https://github.com/edaa-org/pyEDAA.ProjectModel/blob/master/doc/License.rst

.. # GHPages - read now
.. |SHIELD:svg:ProjectModel-ghp-doc| image:: https://img.shields.io/website?longCache=true&style=flat-square&label=edaa-org.github.io%2FpyEDAA.ProjectModel&logo=GitHub&logoColor=fff&up_color=blueviolet&up_message=Read%20now%20%E2%9E%9A&url=https%3A%2F%2Fedaa-org.github.io%2FpyEDAA.ProjectModel%2Findex.html
   :alt: Documentation - Read Now!
   :height: 22
   :target: https://edaa-org.github.io/pyEDAA.ProjectModel/
.. |SHIELD:png:ProjectModel-ghp-doc| image:: https://raster.shields.io/website?longCache=true&style=flat-square&label=edaa-org.github.io%2FpyEDAA.ProjectModel&logo=GitHub&logoColor=fff&up_color=blueviolet&up_message=Read%20now%20%E2%9E%9A&url=https%3A%2F%2Fedaa-org.github.io%2FpyEDAA.ProjectModel%2Findex.html
   :alt: Documentation - Read Now!
   :height: 22
   :target: https://edaa-org.github.io/pyEDAA.ProjectModel/

.. # Gitter 
.. |SHIELD:svg:ProjectModel-gitter| image:: https://img.shields.io/badge/chat-on%20gitter-4db797.svg?longCache=true&style=flat-square&logo=gitter&logoColor=e8ecef
   :alt: Documentation License
   :height: 22
   :target: https://gitter.im/hdl/community
.. |SHIELD:png:ProjectModel-gitter| image:: https://raster.shields.io/badge/chat-on%20gitter-4db797.svg?longCache=true&style=flat-square&logo=gitter&logoColor=e8ecef
   :alt: Documentation License
   :height: 22
   :target: https://gitter.im/hdl/community
